# file:   .travis.yml (igsn-json)
# author: Jess Robertson
# date:   May 2020

language: python

python:
  - "3.6"
  - "3.7"

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - LC_ALL=C.UTF-8
    - LANG=C.UTF-8
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  # Install everything with our pipenv
  - pip install pipenv
  - pipenv install --ignore-pipfile --dev

# command to run tests
script:
  - pipenv run pytest
